// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/shivaji17/notionbackup/src/config"

	mock "github.com/stretchr/testify/mock"
)

// ConfigOption is an autogenerated mock type for the ConfigOption type
type ConfigOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ConfigOption) Execute(_a0 context.Context, _a1 *config.Config) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewConfigOption interface {
	mock.TestingT
	Cleanup(func())
}

// NewConfigOption creates a new instance of ConfigOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConfigOption(t mockConstructorTestingTNewConfigOption) *ConfigOption {
	mock := &ConfigOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
